Proyecto1/website/auth.py
from flask import *
from flask_mysqldb import MySQL
from datetime import datetime
import hashlib
from PIL import Image
import base64
from io import *
from MySQLdb import IntegrityError
import cv2
from bson.objectid import ObjectId
from bson.binary import Binary


from . import dbmysql
from . import dataSetMongo
from . import r
from . import dbNeo4j
from . import dbMongo


auth = Blueprint('auth',__name__)
# Logica para cuando se ingresa a la aplicacion
@auth.route('/login',methods =['GET','POST'])
def login():
    
    if request.method == 'POST':
        #se trae el username y la contraseña
        username  =request.form.get('username')
        password =request.form.get('password')
        #Se hashea la contraseña para que se guardada con seguridad
        hashed_password = hashlib.sha256(password.encode('utf-8')).hexdigest()
        #Se crea un cursor con la conexion abierta de MySql donde se trae el username y la contraseña
        cursor = dbmysql.connection.cursor()
        queryLogin = "SELECT COUNT(*) FROM usuarios WHERE username=%s AND password=%s"
        cursor.execute(queryLogin, (username, hashed_password))
        result = cursor.fetchone()[0]
        #Si encuentra un match devuelve un 1 significa que estan correctos
        if result == 1:
            # se trae todo la informacion del usuario a a mostar en la pagina Usuario
            query = "SELECT * FROM usuarios WHERE username=%s"
            cursor.execute(query, (username,))
            row = cursor.fetchone()
            id = row[0]
            nombreCompleto = row[3]
            fechaNacimietno = row[4]

            #se trae la foto de perfil y se codifica para mostrar en la pagina web.
            query = "SELECT picture_data FROM pictures WHERE id=%s"
            cursor.execute(query, (id,))
            image_data = cursor.fetchone()[0]
            image_buffer = BytesIO(image_data)
            base64_image = base64.b64encode(image_buffer.getvalue()).decode()
            #se cierra la conexion
            cursor.close()
            #se mustra la pagina usuario
            return render_template("usuario.html",foto=base64_image,username=username,name=nombreCompleto,fecha=fechaNacimietno)
        else:
            # no se encontro match entre el usuario y contraseña ingresado y devuelve error
            cursor.close()
            flash('Error al ingresar Usuario o constraseña invalida ', 'error')
            return render_template("login.html")
   
    
    
    return render_template("login.html")

#logica para registrarse en la aplicacion
@auth.route('/sign-up',methods =['GET','POST'])
def sign_up():
    # si se le da registrar trae los datos desde los inputs del HTML
    if request.method == 'POST':
        
        username =request.form.get('username')
        password  =request.form.get('password')
        nombre =request.form.get('nombre')
        fecha =request.form.get('fecha')
        foto  = request.files['foto']
        #si esta alguno vacio muestra que hubo un error que faltan datos

        if not username or not password or not nombre or not fecha or not foto.filename:
            flash('No ingreso los datos nesesarios ', 'error')
            return render_template("sign_up.html")
        else:
            try:
                # Se encrypta la contraseña
                hashed_password = hashlib.sha256(password.encode('utf-8')).hexdigest()

                cursor = dbmysql.connection.cursor()
                # query inserta el usuario en la base de datos
                cursor.execute(''' INSERT INTO usuarios (username, password, nombreCompleto, fechaNacimiento) VALUES(%s,%s,%s,%s)''',(username ,hashed_password,nombre,fecha))
                dbmysql.connection.commit()

                # Se le y parsea la foto para guardar en la base de datos mysql
                img_data = foto.read()
                img_base64 = base64.b64encode(img_data).decode('utf-8')
                img = Image.open(BytesIO(img_data))
                # query insertar la imagen en la base de datos
                query = "INSERT INTO pictures (username,picture_data) VALUES (%s, %s)"
                cursor.execute(query, (username,img_data))
                dbmysql.connection.commit()
                queryId = "SELECT id FROM usuarios WHERE username=%s"
                cursor.execute(queryId, (username,))
                row = cursor.fetchone()
                id = row[0]
                cursor.close()
                properties = {'id': id, 'username': username}
                label = "Usuarios"
                with dbNeo4j.session() as session:
                    session.run(f"CREATE (n:{label} $properties) RETURN n", properties=properties)
                flash("Creacion de usuario con exito", 'success')
                return redirect('/')
            
            except IntegrityError as e:
                flash('Error al registrarse '+str(e), 'error')
                return redirect('/')
            
    return render_template("sign_up.html")

@auth.route('/update',methods =['GET','POST'])
def update():
    # se traen los datos de la base de datos MySql
    if request.method == 'GET':
            username = request.args.get('username')
            cursor = dbmysql.connection.cursor()
            query = "SELECT * FROM usuarios WHERE username=%s"
            cursor.execute(query, (username,))
            row = cursor.fetchone()
            password = row[2]
            nombreCompleto = row[3]
            fechaNacimietno = row[4]
            cursor.close()
            # se muestra la pagina con los datos acutales del usuario
            return render_template('update.html', username=username,password=password,nombre=nombreCompleto,fecha=fechaNacimietno,foto=None)
    if request.method == 'POST':
        # si se cambio algo se registra el cambio y se guarda en  la base de datos.
        username = request.args.get('username')
        cursor = dbmysql.connection.cursor()
        query = "SELECT password FROM usuarios WHERE username=%s"
        cursor.execute(query, (username,))
        hashPassword = cursor.fetchone()[0]
        password  =request.form.get('password')
        nombre =request.form.get('nombre')
        fecha =request.form.get('fecha')
        foto  = request.files['foto']
        #si se subio una foto se cambia por la nueva
        if  foto.filename:
            img_data = foto.read()
            img_base64 = base64.b64encode(img_data).decode('utf-8')
            img = Image.open(BytesIO(img_data))

            query = "UPDATE pictures SET picture_data=%s WHERE username=%s"
            cursor.execute(query, (img_data,username,))
            dbmysql.connection.commit()
        #si es diferetne se cambia la constraseña
        if hashPassword != password:
            hashed_password = hashlib.sha256(password.encode('utf-8')).hexdigest()
            query = "UPDATE usuarios SET password=%s WHERE username=%s"
            cursor.execute(query, (hashed_password,username,))
            dbmysql.connection.commit()

        query = "UPDATE usuarios SET nombreCompleto=%s, fechaNacimiento=%s WHERE username=%s"
        cursor.execute(query, (nombre,fecha,username,))
        dbmysql.connection.commit()
        
    flash("Cambio en datos de usuario con exito", 'success')
    return render_template('home.html')
        

@auth.route('/usuario',methods =['GET','POST'])
def usuario():
    #se traen los datos del usuario que huzo login y se myestrna en la pagina
    username = request.args.get('username')
    cursor = dbmysql.connection.cursor()
    queryLogin = "SELECT COUNT(*) FROM usuarios WHERE username=%s"
    cursor.execute(queryLogin, (username,))
    result = cursor.fetchone()[0]
    if result == 1:
        query = "SELECT * FROM usuarios WHERE username=%s"
        cursor.execute(query, (username,))
        row = cursor.fetchone()
        id = row[0]
        nombreCompleto = row[3]
        fechaNacimietno = row[4]

            
        query = "SELECT picture_data FROM pictures WHERE id=%s"
        cursor.execute(query, (id,))
        image_data = cursor.fetchone()[0]
        image_buffer = BytesIO(image_data)
        base64_image = base64.b64encode(image_buffer.getvalue()).decode()
        cursor.close()
        return render_template("usuario.html",foto=base64_image,username=username,name=nombreCompleto,fecha=fechaNacimietno)

@auth.route('/dataset',methods =['GET','POST'])
def dataset():
    #se trae el usaurio actual
    username = request.args.get('username')
    if request.method == 'POST':
        #boton de busqueda por de los datasets por nombre  usando regex  

        if 'NomButton' in request.form:
            nombreDescripcion  =request.form.get('nombre')
            if nombreDescripcion == '':
                return render_template('dataset.html', username=username)
            else:
                documents = dataSetMongo.find({"nombre": {"$regex": nombreDescripcion}})
                return render_template('buscarDataset.html', documents=documents,username=username)

        #boton de busqueda por de los datasets por usuarios  usando regex  
        if 'UsButton' in request.form:
            nombreDescripcion  =request.form.get('username')
            if nombreDescripcion == '':
                return render_template('dataset.html', username=username)
            else:
                documents = dataSetMongo.find({"username": {"$regex": nombreDescripcion}})
                return render_template('buscarDataset.html', documents=documents,username=username)
       
        #boton de busqueda por de los datasets por del usaurio activo     
        if 'MiButton' in request.form:
            nombreDescripcion  =request.args.get('username')
            if nombreDescripcion == '':
                return render_template('dataset.html', username=username)
            else:
                
                documents = dataSetMongo.find({"username": nombreDescripcion})

Proyecto1/website/templates/amigos.html
{% extends "base.html" %} {% block title %}Usuario{% endblock %} {% block content
    %}
    
    <div>
      
      <h2>Username: <span>{{ username }}</span></h2>
      <br>
    </div>
      <ul>
        {% if listAmigos != [] %}
      <h2 style="text-align: left; margin-left: -40px;">Seguidos: </h2>
      <br>
          {% for list in listAmigos %}
          <li>{{ list }}</li>
          {% endfor %}
        {% else %}
          <h2>Todavia no sigues a nadie!</h2>
        {% endif %}
        
      </ul>
    
    <form method="POST">
      <div class="form-group">
        <label for="addAmigo">Agregar Amigo</label>
        <input
          type="text"
          class="form-control"
          id="addAmigo"
          name="addAmigo"
          placeholder="Agregar amigo"
        />
        <br>
        <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="addButton">Agregar</button>
      </div>
      <div class="form-group">
        <label for="deleteAmigo">Borrar Amigo</label>
        <input
          type="text"
          class="form-control"
          id="deleteAmigo"
          name="deleteAmigo"
          placeholder="Borrar amigo"
        />
        <br>
        <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="deleteButton">Borrar</button>
      </div>
    </form>
    <br>
    <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.usuario", username=username)}}'">Volver</button>
    {% endblock %}

Proyecto1/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Link a la estilizacion de CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
    <!-- Alertas error en rojo, otro verde  -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>


  </body>
</html>

Proyecto1/website/templates/buscarDataset.html
{% extends "base.html" %} {% block title %}BuscarDataset{% endblock %} {% block content
    %}
    
    <body>
      <h1>Datasets</h1>
      {% for document in documents %}
          <h2>Nombre del Dataset: <span>{{ document["nombre"] }}</span></h2>
          <p>Id del Dataset: <span>{{ document["id"] }}</span></p>
          <p>Usuario dueño del Dataset: <span>{{ document["username"] }}</span></p>
          <p>Descirpcion: <span>{{ document["descripcion"] }}</span></p>
          <p>Fecha de creacion: <span>{{ document["date"] }}</span></p>
  
            {% if username == document["username"] %}
            <p>Numero de Descargas: <span>{{ document["descargas"] }}</span></p>
            <p>Numero de Usuario que han descargado el dataset: </p>
            <ul>
              {% for usuDown in document["usuariosDownload"] %}
                <li>{{ usuDown }}</li>
              {% endfor %}
            </ul>
            <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.clonarDataset", idDocumento=document["id"], username=username)}}'">Clonar</button>
            {% endif %}
          
          <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.verDataset", idDocumento=document["id"], username=username)}}'">Ver</button>
          
          <br><br>
          {% endfor %}
          
    </body>
    <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.dataset", username=username)}}'">Volver</button>
    {% endblock %}

Proyecto1/website/templates/clonarDataset.html
{% extends "base.html" %} {% block title %}verDataSet{% endblock %} {% block content
    %}
    <form method="POST" >
      <h3 align="center">Clonar Dataset</h3>
      <h2>Nombre del Dataset a clonar: <span>{{ nombre }}</span></h2>
      <div class="form-group">
        <label for="nombre">Nuevo nombre</label>
        <input
          type="text"
          class="form-control"
          id="nombre"
          name="nombre"
          placeholder="Enter username"
        />
      </div>
      <button type="submit" style="margin-left: 20px;" class="btn btn-primary"name="clonButton">Clonar</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.dataset", username=username)}}'">Volver</button>

    </form>
    
    {% endblock %}

Proyecto1/website/templates/crearDataset.html
{% extends "base.html" %} {% block title %}CrearDataSet{% endblock %} {% block content
    %}
    <br><br>
    <form method="POST" enctype="multipart/form-data">
      <h3 align="center">Crear DataSet</h3>
      <div class="form-group">
        <label for="Nombre">Nombre</label>
        <input
          type="text"
          class="form-control"
          id="nombre"
          name="nombre"
          placeholder="Ingrese nombre de Dataset"
        />
      </div>
      <div class="form-group">
        <label for="Descripcion">Descripcion</label>
        <textarea
          type="text"
          class="form-control"
          id="descripcion"
          name="descripcion"
          placeholder="Ingrese descripcion"
        ></textarea>
      </div>
      <div class="form-group" >
        <label for="Foto">Foto</label>
        <input
          type="file"
          class="form-control"
          id="foto"
          name="foto"
          placeholder="Selecione foto para el dataSet"
          accept="image/jpeg"
        />
      </div>
      <div class="form-group" >
        <label for="Archivo">Archivo</label>
        <input
          type="file"
          class="form-control"
          id="archivo"
          name="archivo"
          placeholder="Selecione archivo del DataSet"
          accept="text/plain"
        />
      </div>
      <div class="form-group" >
        <label for="Video">Video</label>
        <input
          type="file"
          class="form-control"
          id="video"
          name="video"
          placeholder="Selecione video del DataSet"
          accept="video/mp4"
        />
      </div>
      <br />
      <button type="submit" style="margin-left: 20px;" class="btn btn-primary">Crear</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.dataset", username=username)}}'">Volver</button>
    </form>
    {% endblock %}

Proyecto1/website/templates/dataset.html
{% extends "base.html" %} {% block title %}DataSet{% endblock %} {% block content
    %}
    <h1>DataSet</h1>
    <form method="POST">
      <h3 align="left">Crear DataSet</h3>
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.crearDataset", username=username)}}'">Crear Dataset</button>
      <br><br> 
      <br>
      <h3 align="left">Ver mis DataSet</h3>
      <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="MiButton">Buscar</button>
      <br><br>
      <h3 align="left">Buscar DataSet por nombre</h3>
      <div class="form-group">
        <input
          type="text"
          class="form-control"
          id="nombre"
          name="nombre"
          placeholder="Ingrese Data Set a Buscar"
        />
        <br>
        <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="NomButton">Buscar</button>
      </div>
      <h3 align="left">Buscar DataSet por descripion</h3>
      <div class="form-group">
        <input
          type="text"
          class="form-control"
          id="Descripcion"
          name="Descripcion"
          placeholder="Ingrese Data Set a Buscar"
        />
        <br>
        <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="DesButton">Buscar</button>
      </div>
      <h3 align="left">Buscar DataSet de Usuario</h3>
      <div class="form-group">
          <input
            type="text"
            class="form-control"
            id="username"
            name="username"
            placeholder="Ingrese Data Set a Buscar"
          />
          <br>
          <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="UsButton">Buscar</button>
        </div>
        <br>
        <br>
        <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.usuario", username=username)}}'">Volver</button>
    </form>
    {% endblock %}

Proyecto1/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1>Proyecto 1 Bases de Datos 2</h1>

    <button type="button"  style="margin-left: 20px;" class="btn btn-primary" onclick="window.location.href='http://127.0.0.1:5000/login';" >Login</button>
    <button type="button" style="margin-left: 20px;" class="btn btn-primary" onclick="window.location.href='http://127.0.0.1:5000/sign-up';" >Sign-up</button>
     
        
      
      
    {% endblock %}

Proyecto1/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="username">Usuario</label>
        <input
          type="text"
          class="form-control"
          id="username"
          name="username"
          placeholder="Ingrese Usuario"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" style="margin-left: 20px;" class="btn btn-primary">Login</button>
      <button type="button" style="margin-left: 20px;" class="btn btn-primary" onclick="window.location.href='http://127.0.0.1:5000/';" >Atras</button>
    </form>
    {% endblock %}

Proyecto1/website/templates/notificaciones.html
{% extends "base.html" %} {% block title %}Notificaciones{% endblock %} {% block content
    %}
    <h1>Notificaciones: </h1>
    <table  class="table table-striped">
      <thead class="thead-light">
        <tr>
          <th scope="col">Nombre del DataSet</th>
          <th scope="col">Usuario</th>
          <th scope="col">Borrar</th>
          <th scope="col">Ver</th>
        </tr>
      </thead>
      <tbody>
        {% for i in DataSet %}
        <tr>
          
          <td>{{ i[0] }}</td>
          <td>{{ i[1] }}</td>
          <td>
            <form action="{{ url_for('auth.notificaciones', idDocumento =i[2], username=username) }}" method="POST">
              <button type="submit">Delete</button>
            </form>
          </td>
          <td>
            
            <form action="{{ url_for('auth.verDataset', idDocumento =i[2], username=username) }}" method="POST">
              <button type="submit" name="NotifButton">Ver Dataset</button>
            </form>
          </td>
          
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.usuario", username=username)}}'">Volver</button>

    {% endblock %}

Proyecto1/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST" enctype="multipart/form-data">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="username">Username</label>
        <input
          type="text"
          class="form-control"
          id="username"
          name="username"
          placeholder="Enter username"
        />
      </div>
      <div class="form-group">
        <label for="password">Contraseña</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Ingrese contraseña"
          
        />
      </div>
      <div class="form-group">
        <label for="Nombre">Nombre Completo</label>
        <input
          type="text"
          class="form-control"
          id="nombre"
          name="nombre"
          placeholder="Ingrese nombre completo"
        />
      </div>
      <div class="form-group">
        <label for="Fecha">Fecha</label>
        <input
          type="date"
          class="form-control"
          id="fecha"
          name="fecha"
          placeholder="Ingrese fecha naciemiento"
        />
      </div>
      <div class="form-group" >
        <label for="Foto">Foto</label>
        <input
          type="file"
          class="form-control"
          id="foto"
          name="foto"
          placeholder="Selecione foto de perfil"
          accept="image/jpeg"
        />
      </div>
      <br />
      <button type="submit" style="margin-left: 20px;" class="btn btn-primary">Registrarse</button>
      <button type="button" style="margin-left: 20px;" class="btn btn-primary" onclick="window.location.href='http://127.0.0.1:5000/';" >Atras</button>
    </form>
    {% endblock %}

Proyecto1/website/templates/update.html
{% extends "base.html" %} {% block title %}Update{% endblock %} {% block
    content %}
    <form method="POST" enctype="multipart/form-data">
        <h3 align="center">Modificar Informacion</h3>
        <h2>Username: <span>{{ username }}</span></h2>
        <div class="form-group">
          <label for="password">Contraseña</label>
          <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Ingrese contraseña"
            value="{{ password }}"
          />
        </div>
        <div class="form-group">
          <label for="Nombre">Nombre Completo</label>
          <input
            type="text"
            class="form-control"
            id="nombre"
            name="nombre"
            placeholder="Ingrese nombre completo"
            value="{{ nombre }}"
          />
        </div>
        <div class="form-group">
          <label for="Fecha">Fecha</label>
          <input
            type="date"
            class="form-control"
            id="fecha"
            name="fecha"
            placeholder="Ingrese fecha naciemiento"
            value="{{ fecha }}"
          />
        </div>
        <div class="form-group" >
          <label for="Foto">Foto</label>
          <input
            type="file"
            class="form-control"
            id="foto"
            name="foto"
            placeholder="Selecione foto de perfil"
            value="{{ foto }}"
            accept="image/jpeg"
          />
        </div>
        <br />
        <button type="submit" style="margin-left: 20px;" class="btn btn-primary">Modificar</button>
        <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.usuario", username=username)}}'">Volver</button>
      </form>
    {% endblock %}


    value="{{ default_password }}"

Proyecto1/website/templates/usuario.html
{% extends "base.html" %} {% block title %}Usuario{% endblock %} {% block content
    %}
    <div>
      <br>
      <br>
      <img src="data:image/jpeg;base64,{{ foto }}" alt="Image" width="200 " height="200 " />
      <br>
      <br>
      <h2>Username: <span>{{ username }}</span></h2>
      <p>Nombre Completo: <span>{{ name }}</span></p>
      <p>Fecha de cumpleaños: <span>{{ fecha }}</span></p>
      
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.update", username=username)}}'">Modificar</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.dataset", username=username)}}'">DataSet</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.amigos", username=username)}}'">Seguidos</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.notificaciones", username=username)}}'">Notificaciones</button>
    </div>
    <br><br>
    <button type="button" style="margin-left: 20px;" class="btn btn-primary" onclick="window.location.href='http://127.0.0.1:5000/';" >Salir</button>
    {% endblock %}

Proyecto1/website/templates/verDataset.html
{% extends "base.html" %} {% block title %}verDataSet{% endblock %} {% block content
    %}
    <div>
      <br><br>
      <img src="data:image/jpeg;base64,{{ foto }}" alt="Image" width="200 " height="200 " />
      <br><br>
      <h2>Nombre del Dataset: <span>{{ nombre }}</span></h2>
      <p>Descirpcion: <span>{{ descripcion }}</span></p>
      <p>Fecha de creacion: <span>{{ fecha }}</span></p>
      <p>Tamaño del DataSet: <span>{{ size }}</span></p>
      <div>
      <h2>Archivo del Dataset : </h2>
      <textarea style="height: 200px; width: 100%; overflow: auto;" readonly>{{ archivo }}</textarea>
      <br><br>
      <form method="POST">
      <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="DownlodButton">Descargar</button>
      </form>
      </div>
      <div>
        <h2>Video del Dataset: </h2>
        <video width="640" height="480" controls>
            <source src="data:video/mp4;base64,{{ video_base64 }}" type="video/mp4">
        </video>
      </div>
      <form method="POST">
      <h2>Comentarios: </h2>
      <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="ComenButton">Comentar</button>
     </form>
      <br><br>
      <form method="POST">
      <h2>Mi puntuacion: </span></h2>
        <div class="form-group">
          <label for="password">puntuacion</label>
          <input
            type="text"
            class="form-control"
            id="puntuacion"
            name="puntuacion"
            placeholder="Ingrese puntuacion"
            value="{{ puntuacion }}"
          />
        </div>
        <button type="submit" style="margin-left: 20px;" class="btn btn-primary" name="punButton">Votar</button>
      </form>
      <br><br>
      <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for("auth.dataset", username=username)}}'">Volver</button>
    </div>
    
    {% endblock %}